spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  cache:
#    CacheType.xx
#    type: simple
    type: redis
    cache-names: starbucks
    time-to-live: 5000
    cache-null-values: false
  redis:
    host: localhost
    lettuce:
      pool:
        maxActive: 5
        maxIdle: 5