spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  redis:
    host: localhost
    lettuce:
      pool:
        maxActive: 5
        maxIdle: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'